version: '2.0'

services:
  sjbha-app:
    build: .
    env_file: /etc/sjbha.s3bby.env
    environment:
      NODE_ENV: "production"
      DEBUG: "@services*,@app:*,@plugins:*"
      HOSTNAME: "https://sjbha.s3bby.com"
      VIRTUAL_HOST: "sjbha.s3bby.com"
      VIRTUAL_PORT: 5000

    ports:
      - "5000:5000"
    networks:
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy